services:
  - type: worker
    name: bot-trading-vivo
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python bot_trading_live_pro.py
    pythonVersion: 3.10.12
